---
title: CASSIE MARIE | AUTHOR
timezone: America/Chicago
theme: just-the-docs
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
  - jekyll-seo-tag
- jekyll-sitemap
